receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  memory_limiter:
    limit_mib: 1024
    spike_limit_mib: 256
    check_interval: 5s
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/tempo]

extensions:
  health_check: {}
