global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector-201:8888"]

remote_write:
  - url: "http://mimir-201:9009/api/v1/push"
